### ISSUE TITLE
Extensions CLI Commands

### ISSUE THREAD

**Issue by GheorgheP** [ThemeFuse/Unyson-CLI#1]
Hi all,

I need your help.
I think all extensions commands will go via `wp unyson ext <ext-name> <ext-command>`.

The extension that will implement CLI commands will defined them in `cli` folder that will be located in extension root.

There will be some reserved commands that the extensions will not be able to implement, like:

 - activate
 - deactivate
 - install
 - uninstall
 - version
 - update
 - upgrade
 - downgrade
 - manifest
 - status

Please tell me what do you think, what may not work, or any other suggestions.

**Comment by GheorgheP** [comment]
Paritial implementation: https://github.com/ThemeFuse/Unyson-CLI/commit/1203fab7509bdd1033a9ad32901c35adbd421b88

**Comment by andreiglingeanu** [comment]
We don't have a `wp unyson exts list` command? I don't see a way to list all available extensions.

There are 3 categories of extensions:

- `available` - extensions listed in [`available-extensions.php`](https://github.com/ThemeFuse/Unyson/blob/v2.6.16/framework/core/components/extensions/manager/available-extensions.php) or in [`{theme}/framework-customizations/theme/available-extensions.php`](https://github.com/ThemeFuse/Unyson/blob/v2.6.16/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L215-L222) but not installed
- `installed` - the ones present in installed locations but not activated
- `activated` - the ones that are installed and activated

I think we need to defined flags for `list` command that will allow us to filter them out.

**Comment by andreiglingeanu** [comment]
About that `wp unyson ext <ext-name> <ext-command>` - I definitely like the automatic namespacing of it, this idea is amazing!

What if we mark the reserved commands methods as `final` in [`\Unyson\Extension\Command`](https://github.com/ThemeFuse/Unyson-CLI/blob/404b5f7b7dd0422bfd249619c881113c1aef1c62/src/Extension/Command.php). I think this will give enough safety.

**Comment by andreiglingeanu** [comment]
Also, it will be nice to have a `path` command for each command, just like we do for `wp unyson path --dir`.

**Comment by GheorgheP** [comment]
About `list`, I implemented it on m local but forgot to commit, I will review and push it.
About `path`, this is a global cli parameter, and it should work, for now I did not test it out so I cannot confirm.
