### ISSUE TITLE
Can I install Unyson's extensions using CLI

### ISSUE THREAD

**Issue by kumaxim** [ThemeFuse/Unyson-CLI#10]
Good evening.
The question in the title. 
I tried to use `wp plugin install https://github.com/ThemeFuse/Unyson-Mailer-Extension.git` and `wp unyson install https://github.com/ThemeFuse/Unyson-Mailer-Extension.git`. I tried replace git-repo to zip-archive. There aren't help me to install extension. I know I am able to update them, but How can I install in CLI mod?

**Comment by andreiglingeanu** [comment]
Yes, just use `wp unyson exts` command. For example, you can run `wp unyson exts shortcodes install` to install the `shortcodes extension.

Also, you can run `wp unyson exts list` to see an overview of supported extensions.
