### ISSUE TITLE
update and upgrade commands

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson-CLI#3]
What is the difference between [update](https://github.com/ThemeFuse/Unyson-CLI#update-wp-unyson-update) and [upgrade](https://github.com/ThemeFuse/Unyson-CLI#upgrade-wp-unyson-upgrade) commands?

I see their names being very similar and the difference between them is not very clear.

**Comment by GheorgheP** [comment]
As is mentioned in commands description.

 - **Update** - updates Unyson/extension to the latest version
 - **Upgrade** - updates Unyson/extension to the next available version - this is more useful for testing. Let's say you are on version `2.4.13` and want to switch to next closes version `2.4.14`. This is a short hand of of the `wp unyson update --version=specific-version`.

It goes in pair with `wp unyson downgrade`.
