### ISSUE TITLE
Install command suggestion

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson-CLI#4]
I see the `install` command being a simple alias to `wp plugin install` and it is working only with the version of the plugin from wordpress.org.

I think that `edge` version should be listed in [`wp unyson versions`](https://github.com/ThemeFuse/Unyson-CLI#versions-wp-unyson-versions) too.

What if we introduce a `--edge` flag for in order to be able to install latest `master` version of unyson. This flag will make the life easier for a lot of people who open issues publicly on GitHub, it will be easier for them to update to latest changes.

**Comment by GheorgheP** [comment]
I think this is a good idea.
