### ISSUE TITLE
Can't add package to wp cli

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson-CLI#5]
Hello guys.
I try to add the wp unyson package and get the following error :

```
wp package install https://github.com/ThemeFuse/Unyson-CLI unyson-cli
Error: Invalid package.
```

Here is my wp cli info :
```
wp --info
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.15-0ubuntu0.16.04.4
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/nex
WP-CLI packages dir:	/home/tolea/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.2.1
```

**Comment by GheorgheP** [comment]
Yes
It turns out that in order to be able to install it the package version needs to be stable.
You can install it using the zip file: https://github.com/ThemeFuse/Unyson-CLI/archive/master.zip

**Comment by ViorelEremia** [comment]
you can try:
 ```wp package install themefuse/unsyson-cli```
 or 
``` wp package install git@github.com:ThemeFuse/Unyson-CLI.git```
