### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by jonah** [ThemeFuse/Unyson-CLI#7]
If I use the instructions I get:

wp package install https://github.com/ThemeFuse/Unyson-CLI unyson-cli
Error: Too many positional arguments: unyson-cli

I'm using wp cli version 1.4.  

If I do:
wp package install ThemeFuse/Unyson-CLI

Problem 1
    - The requested package themefuse/unyson-cli could not be found in any version, there may be a typo in the package name.

**Comment by ViorelEremia** [comment]
you can try:
 ```wp package install themefuse/unsyson-cli```
 or 
``` wp package install git@github.com:ThemeFuse/Unyson-CLI.git```
