### ISSUE TITLE
Extensions update error

### ISSUE THREAD

**Issue by jonah** [ThemeFuse/Unyson-CLI#9]
I'm getting the following error when trying to get extensions to update:

wp unyson exts update
PHP Fatal error:  Call to private method FW_Extension_Update::get_extensions_with_updates() from context 'Unyson\Commands\Extensions' in /home/jonah/.wp-cli/packages/vendor/themefuse/unyson/src/Commands/Extensions.php on line 192
Fatal error: Call to private method FW_Extension_Update::get_extensions_with_updates() from context 'Unyson\Commands\Extensions' in /home/jonah/.wp-cli/packages/vendor/themefuse/unyson/src/Commands/Extensions.php on line 192

My wp cli is version 1.5.0

Thanks.

**Comment by ViorelEremia** [comment]
Have you the latest version of unyson? I tried and it is working. this function is public: https://github.com/ThemeFuse/Unyson/blob/master/framework/extensions/update/class-fw-extension-update.php#L157

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
